version: '3.8'

services:
  food-delivery-analyzer:
    image: yourusername/food-delivery-analyzer:latest
    volumes:
      - ./data:/app/data
    environment:
      - SCHEDULE_INTERVAL=24  # Run every 24 hours
    restart: unless-stopped

  frontend:
    image: yourusername/food-delivery-frontend:latest
    ports:
      - "3000:3000"  # Map port 3000 to host
    volumes:
      - ./data:/app/data  # Share the data directory
    depends_on:
      - food-delivery-analyzer